### ISSUE TITLE
This lab requires "self," which hasn't been introduced yet

### ISSUE THREAD

**Issue by dagonyclark** [learn-co-students/keys-of-hash-prework#291]
Unless I'm missing something, use of "self" hasn't been taught in any lesson or lab. I knew about it from prior CS knowledge and guessed that it might work here.

**Comment by sgharms** [comment]
I searched all the text files and couldn't find the word `self` anywhere.  I looked at your solution, which did use `self`, but it works fine without `self.`. Could you please clarify the issue here?

**Comment by dagonyclark** [comment]
Apologies, I just didn't know how to solve it then. I should have checked the solution branch after my solution worked.
